### ISSUE TITLE
Error that occurs in getValue() 

### ISSUE THREAD

**Issue by JeremyCSUMB** [AKor1110/CST336_SilverJack#2]
Fatal error: Call to a member function getValue() on a non-object in /home/ubuntu/workspace/CST336_SilverJack/core/Player.php on line 55 Call Stack: 0.0003 233896 1. {main}() /home/ubuntu/workspace/CST336_SilverJack/index.php:0 0.0006 271384 2. Game->play() /home/ubuntu/workspace/CST336_SilverJack/index.php:20 0.0011 273240 3. Player->addCard() /home/ubuntu/workspace/CST336_SilverJack/core/Game.php:44

**Comment by AKor1110** [comment]
Resolved. Issue with player's hit() function returning true indefinitely, fixed by adding a condition where we only want to hit if the player's score is < 42 and some difference logic.
